@ECHO OFF
PUSHD %~dp0

IF "%SPHINXBUILD%"=="" SET SPHINXBUILD=sphinx-build
IF "%~1"=="" (SET TARGET=help) ELSE (SET TARGET=%~1)

%SPHINXBUILD% -M %TARGET% . _build
SET STATUS=%ERRORLEVEL%

POPD
EXIT /B %STATUS%
